tests:
	swipl c03.pl | diff results/c03.txt -
	swipl c04.pl | diff results/c04.txt -
	swipl c06.pl | diff results/c06.txt -
	swipl c07.pl | diff results/c07.txt -
	swipl c08.pl | diff results/c08.txt -
	swipl l03.pl | diff results/l03.txt -
	swipl l04.pl | diff results/l04.txt -
	swipl l05.pl | diff results/l05.txt -
	swipl l06.pl | diff results/l06.txt -
	swipl l07.pl | diff results/l07.txt -
	swipl l08.pl | diff results/l08.txt -
	swipl l09.pl | diff results/l09.txt -
	swipl l10.pl | diff results/l10.txt -
	swipl l11.pl | diff results/l11.txt -
	swipl l12.pl | diff results/l12.txt -
	swipl l13.pl | diff results/l13.txt -
	swipl l14.pl | diff results/l14.txt -
	swipl l15.pl | diff results/l15.txt -
	swipl l16.pl | diff results/l16.txt -
	swipl l17.pl | diff results/l17.txt -
	swipl l18.pl | diff results/l18.txt -
	make clean
r:
	swipl l03.pl > results/l03.txt
	swipl l04.pl > results/l04.txt
	swipl l05.pl > results/l05.txt
	swipl l06.pl > results/l06.txt
	swipl l07.pl > results/l07.txt
	swipl l08.pl > results/l08.txt
	swipl l09.pl > results/l09.txt
	swipl l10.pl > results/l10.txt
	swipl l11.pl > results/l11.txt
	swipl l12.pl > results/l12.txt
	swipl l13.pl > results/l13.txt
	swipl l14.pl > results/l14.txt
	swipl l15.pl > results/l15.txt
	swipl l16.pl > results/l16.txt
	swipl l17.pl > results/l17.txt
	swipl l18.pl > results/l18.txt
	swipl c03.pl > results/c03.txt
	swipl c04.pl > results/c04.txt
	swipl c06.pl > results/c06.txt
	swipl c07.pl > results/c07.txt
	swipl c08.pl > results/c08.txt
clean:
	rm -rf *.ll *.exe *.s
ll:
	cd c; make ll
