test:
	swipl tests/test_asm.pl
	swipl tests/test_genid.pl
	swipl tests/test_emit.pl
	swipl tests/test_memAlloc.pl
	swipl tests/test_expand.pl
	swipl tests/test_setmem.pl
	make clean
clean:
	rm -rf a a.s
